account/urls.py
from . import views
from django.urls import path
from .views import PostList, PostCreate, PostUpdate, DeletePost, Profile
from django.contrib.auth import views as authviews

app_name = 'account'
urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', authviews.LogoutView.as_view(), name='logout')
]

urlpatterns += [
    path('', PostList.as_view(), name='dashboard'),
    path('newpost/', PostCreate.as_view(), name='create'),
    path('edit/<int:pk>/', PostUpdate.as_view(), name='editpost'),
    path('delete/<int:pk>/', DeletePost.as_view(), name='delpost'),
    path('profile/', Profile.as_view(), name='profile'),
]

blog/urls.py
from django.urls import path
from .views import Home, PostDetail, CategoryList, UserPost, Preview

app_name = 'blog'
urlpatterns = [
    path('', Home.as_view() , name='home'),
    path('page=<int:page>/', Home.as_view() , name='home'),
    path('post/<slug:slug>/', PostDetail.as_view() , name='postdetail'),
    path('category/<slug:slug>/', CategoryList.as_view() , name='category'),
    path('category/<slug:slug>/page=<int:page>/', CategoryList.as_view() , name='category'),
    path('user/<slug:username>/', UserPost.as_view(), name='postsUser'),
    path('user/<slug:username>/page=<int:page>/', UserPost.as_view(), name='postsUser'),
    path('preview/<int:pk>/', Preview.as_view(), name='preview'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls'))
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    is_author = models.BooleanField(default=False, verbose_name="The site user is an author")
    special_user = models.DateTimeField(default=timezone.now, verbose_name="Special user until")
    bio = models.TextField(null=True, blank=True)
    
    def is_special_user(self):
        if self.special_user > timezone.now():
            return True
        else:
            return False
    is_special_user.boolean = True
    is_special_user.short_description = 'special user'

blog/models.py
from django.db import models
from django.utils import timezone
from django.utils.html import format_html
from account.models import User
from django.urls import reverse

# managers
class PostManager(models.Manager):
    def published(self):
        return self.filter(status='p')

class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status=True)
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=300, unique=True, verbose_name='category slug')
    status = models.BooleanField(default=True, verbose_name='to be displayed')
    position = models.IntegerField()
    class Meta:
        verbose_name='categroy'
        ordering = ['position']

    def __str__(self):
        return self.name

    objects = CategoryManager()

class Post(models.Model):
    STATUS_CHOICES = (
        ('d', 'draft'),
        ('p', 'published'),
        ('i', 'investigation'),
        ('b', 'back')
    )
    title = models.CharField(max_length=300, verbose_name='post title')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_user')
    slug = models.SlugField(max_length=400, unique=True, verbose_name='post slug')
    category = models.ManyToManyField(Category, related_name='posts')
    image = models.ImageField(upload_to='images', verbose_name='post image')
    description = models.TextField()
    publish = models.DateTimeField(default=timezone.now, verbose_name='publication date')
    is_special = models.BooleanField(default=False, verbose_name='Special content')
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)

    class Meta:
        verbose_name='Post'
        ordering = ['-publish']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('account:dashboard')

    def category_to_list(self):
        return ", ".join([category.name for category in self.category.filter(status=True)])
    
    def image_tag(self):
        return format_html("<img width=100 height=75  src='{}'>".format(self.image.url))
        
    objects = PostManager()

account/forms.py
from django import forms
from .models import User

class ProfileForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		user = kwargs.pop('user')

		super(ProfileForm, self).__init__(*args, **kwargs)

		self.fields['username'].help_text = None
		
		if not user.is_superuser:
			self.fields['special_user'].disabled = True
			self.fields['is_author'].disabled = True

	class Meta:
		model = User
		fields = ['username', 'email', 'first_name', 'last_name', 'bio', 'special_user', 'is_author']

account/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from .mixins import AuthorsAccessMixin, FieldsMixin, FormValidMixin, AuthorAccessMixin, SuperUserAccessMixin
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from blog.models import Post
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import User
from .forms import ProfileForm

class Login(LoginView):
    template_name = 'account/login.html'
    def get_success_url(self):
        return reverse_lazy('blog:home')
# Create your views here.

class PostList(AuthorsAccessMixin, ListView):
    template_name = 'account/dashboard.html'
    context_object_name = 'posts'

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Post.objects.all()
        else:
            return Post.objects.filter(author= self.request.user)

class PostCreate(AuthorsAccessMixin, FormValidMixin, FieldsMixin, CreateView):
    model= Post
    template_name = 'account/cu_post.html'

class PostUpdate(AuthorAccessMixin, FieldsMixin, FormValidMixin, UpdateView):
    model = Post
    template_name = 'account/cu_post.html'

class DeletePost(SuperUserAccessMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('account:dashboard')
    template_name = 'account/post_confirm_delete.html'

class Profile(LoginRequiredMixin ,UpdateView):
	model = User
	template_name = "account/profile.html"
	form_class = ProfileForm
	success_url = reverse_lazy("account:dashboard")

	def get_object(self):
		return User.objects.get(pk = self.request.user.pk)

	def get_form_kwargs(self):
		kwargs = super(Profile, self).get_form_kwargs()
		kwargs.update({
			'user': self.request.user
		})
		return kwargs

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Post, Category
from account.models import User
from django.shortcuts import get_object_or_404
from account.mixins import AuthorAccessMixin

class Home(ListView):
    queryset = Post.objects.published()
    paginate_by = 4
    context_object_name = 'posts'
    template_name = 'blog/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = Category.objects.active()
        return context

class PostDetail(DetailView):
    context_object_name = 'post'
    template_name= 'blog/post.html'

    def get_object(self):
        slug = self.kwargs.get('slug')
        return get_object_or_404(Post.objects.published(), slug=slug)

class CategoryList(ListView):
    paginate_by = 4
    template_name = 'blog/category_list.html'
    context_object_name = 'posts'

    def get_queryset(self):
        global category
        slug = self.kwargs.get('slug')
        category = get_object_or_404(Category.objects.active(), slug=slug)
        return category.posts.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = category
        return context

class UserPost(ListView):
    paginate_by = 4
    template_name = 'blog/user_posts.html' 
    context_object_name = 'posts'
    def get_queryset(self):
        global author
        username = self.kwargs.get('username')
        author = get_object_or_404(User, username=username)
        return author.post_user.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = author
        return context

class Preview(AuthorAccessMixin, DetailView):
    template_name = 'blog/post.html'
    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Post, pk=pk)

templates/blog/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <!-- navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse mx-auto" id="navbarTogglerDemo01">
        <a class="navbar-brand" href="#">Hidden brand</a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'blog:home' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'account:dashboard'%}">profile</a>
            {% else %}
            <a class="nav-link" href="{% url 'account:login' %}">login/register</a>
            {% endif %}
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
    <!-- navbar -->

    <!-- posts -->
    {% block main %}{% endblock %}
    <!-- posts -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

templates/blog/category_list.html
{% extends 'blog/base.html' %}

{% block main%}
    {% for post in posts %}
        <div class="card mb-3" style="max-width: 540px;">
            <div class="row no-gutters">
                <div class="col-md-4">
                    <img src="{{ post.image.url }}" class="card-img" alt="...">
                    </div>
                    <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">{{ post.title }}</h5>
                        <p class="card-text">{{ post.description }}</p>
                        <p class="card-text"><small class="text-muted"><a href="#">{{ post.author }}</a> | {{ post.publish }}</small></p>
                        <a href="{% url 'blog:postdetail' post.slug %}" class="btn btn-primary">read more</a>
                    </div>
                    
                </div>
            </div>
        </div>
    {% endfor %}
    <!-- pagination -->
    
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="{% url 'blog:category' category.slug page_obj.previous_page_number %}">Previous</a></li>
            {% else %}
                <li class="disabled"><a class="page-link">Previous</a></li>
            {% endif %}
            {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="page-item active"><a class="page-link " >{{ i }}</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="{% url 'blog:category' category.slug i %}">{{ i }}</a></li>
            {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="{% url 'blog:category' category.slug page_obj.next_page_number %}">Next</a></li>
            {% else %}
                <li class="disabled"><a class="page-link">Next</a></li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}

templates/blog/home.html
{% extends 'blog/base.html' %}

{% block main%}
    <h1 style="text-align: center;">posts</h1>
    {% for post in posts %}
    <div class="col-md-6 mx-auto">
        <div class="card mb-3">
            <div class="row no-gutters">
                <div class="col-md-4">
                    <img src="{{ post.image.url }}" class="card-img" alt="...">
                    </div>
                    <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">{{ post.title }}</h5>
                        <p class="card-text">{{ post.description }}</p>
                        <p class="card-text"><small class="text-muted"><a href="{% url 'blog:postsUser' post.author.username %}">{{ post.author.get_full_name }}</a> | {{ post.publish }}</small></p>
                        <a href="{% url 'blog:postdetail' post.slug %}" class="btn btn-primary">read more</a>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- pagination -->
    
    <nav aria-label="Page navigation example" class="col-md-3 mx-auto">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="{% url 'blog:home' page_obj.previous_page_number %}">Previous</a></li>
            {% else %}
                <li class="disabled"><a class="page-link">Previous</a></li>
            {% endif %}
            {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="page-item active"><a class="page-link " >{{ i }}</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="{% url 'blog:home' i %}">{{ i }}</a></li>
            {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="{% url 'blog:home' page_obj.next_page_number %}">Next</a></li>
            {% else %}
                <li class="disabled"><a class="page-link">Next</a></li>
            {% endif %}
        </ul>
    </nav>
    <h1 style="text-align: center;">category</h1>
    <div class="categoris col-md-6 mx-auto" style="display: flex;">
    {% for cat in category%}
        <a href="{% url 'blog:category' cat.slug %}" class="btn btn-secondary" style="margin: 20px;">{{ cat.name }}</a>
    {% endfor %}
    </div>
{% endblock %}

templates/blog/post.html
{% extends 'blog/base.html' %}

{% block main %}
    <div>
        <img style="max-width: 500px;" src="{{ post.image.url }}" alt="">
        <h4>{{ post.title }}</h4>
        <p><a href="{% url 'blog:postsUser' post.author.username %}">{{ post.author }}</a>
            <span>{{ post.publish }}</span>
        </p>
        <p style="border-bottom: 1px solid black;">{{ post.description }}</p>
        <h3>category</h3>
        {% for category in post.category.active %}
        <a href="{% url 'blog:category' category.slug %}">#{{ category.name }}</a>
        {% endfor %}
    </div>
{% endblock %}

templates/blog/user_posts.html
{% extends 'blog/base.html' %}

{% block main%}
<h1 style="margin: 40px;">{{ author.get_full_name }}'s posts</h1>
    {% for post in posts %}
        <div class="card mb-3" style="max-width: 540px;">
            <div class="row no-gutters">
                <div class="col-md-4">
                    <img src="{{ post.image.url }}" class="card-img" alt="...">
                    </div>
                    <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">{{ post.title }}</h5>
                        <p class="card-text">{{ post.description }}</p>
                        <p class="card-text"><small class="text-muted"><a href="{% url 'blog:postsUser' post.author.username %}">{{ post.author.get_full_name }}</a> | {{ post.publish }}</small></p>
                        <a href="{% url 'blog:postdetail' post.slug %}" class="btn btn-primary">read more</a>
                    </div>
                    
                </div>
            </div>
        </div>
    {% endfor %}
    <!-- pagination -->
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="{% url 'blog:postsUser' author.username page_obj.previous_page_number %}">Previous</a></li>
            {% else %}
                <li class="disabled"><a class="page-link">Previous</a></li>
            {% endif %}
            {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="page-item active"><a class="page-link " >{{ i }}</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="{% url 'blog:postsUser' author.username i %}">{{ i }}</a></li>
            {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="{% url 'blog:postsUser' author.username page_obj.next_page_number %}">Next</a></li>
            {% else %}
                <li class="disabled"><a class="page-link">Next</a></li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}